### ISSUE TITLE
New Update.

### ISSUE THREAD

**Issue by Fahi-alt** [devbutlazy/Blum-AutoClicker#15]
![1000273549](https://github.com/user-attachments/assets/40b80da6-3b67-4898-b321-1b36bc622200)
If you click on Bombs you will get +10 points.

**Comment by deyman12** [comment]
@devbutlazy hi dev, kindly update it asap.

**Comment by devbutlazy** [comment]
> @devbutlazy hi dev, kindly update it asap.

Already done in new version 😆

**Comment by deyman12** [comment]
> > @devbutlazy hi dev, kindly update it asap.
> 
> Already done in new version 😆

as @Fahi-alt  mentioned, click the bomb will get 10+ points. kindly pls add for collect bomb and click them too. i suggest you better create new branch, so when blum remove the pumkin event it's more easy to maintenance and clone.

**Comment by devbutlazy** [comment]
> > > @devbutlazy hi dev, kindly update it asap.
> > 
> > Already done in new version 😆
> 
> as @Fahi-alt  mentioned, click the bomb will get 10+ points. kindly pls add for collect bomb and click them too. i suggest you better create new branch, so when blum remove the pumkin event it's more easy to maintenance and clone.

join https://t.me/chatbutlazy and there is already additional part of code pinned for collecting bombs too
