### ISSUE TITLE
https://github.com/devbutlazy/Blum-AutoClicker.git

### ISSUE THREAD

**Issue by Alaminhamji** [devbutlazy/Blum-AutoClicker#5]
https://github.com/devbutlazy/Blum-AutoClicker.git

**Comment by Muhammad815703** [comment]
I don't know how to set it

**Comment by Alaminhamji** [comment]
Please help me start it, I have more than 300 tickets for blum

**Comment by Muhammad815703** [comment]
I also don't know how to start it

**Comment by Alaminhamji** [comment]
To ya zamuyi knn kamin magana ta talegram @alamin_hamji zan tura ma wani

**Comment by Mhgoravop** [comment]
blum auto clicker

**Comment by Mhgoravop** [comment]
https://github.com/devbutlazy/Blum-AutoClicker

**Comment by Mhgoravop** [comment]
https://github.com/user-attachments/assets/d9496bed-c1a0-4a1b-9673-1e64d0441621

**Comment by Mhgoravop** [comment]
- [Duplicate](url) 

- [ ] of #4
